// Codegen: emit src/Generated/Types.cs from the language-neutral JSON Schemas in
// ../../spec, using NJsonSchema (System.Text.Json flavour).
//
// Strategy (mirrors the TypeScript scripts/generate.ts)
// -----------------------------------------------------
// Every schema file in the spec is self-contained: all $ref pointers are internal
// #/$defs/... references (verified — no cross-file refs). So we generate types per
// file and concatenate the results into a single Types.cs, deduplicating shared
// declarations (ErrorObject, ConversationMessage, GeneralAgentResponse, …) that
// several files declare independently.
//
// The envelope and action files are top-level `oneOf` over $defs with the real
// shapes living under $defs (e.g. Request / Response). NJsonSchema flattens a
// top-level oneOf into a single merged class, so instead we extract each named
// $def, carry the $defs map along so internal refs still resolve, and emit each as
// its own root type with a stable title-derived name.
//
// The event and domain files are flat top-level objects (some with their own
// nested $defs, e.g. message.schema.json) and are generated as-is.
//
// NJsonSchema names inline $ref targets after the referencing property by default
// (e.g. `Messages` instead of `ConversationMessage`); a custom TypeNameGenerator
// prefers the referenced schema's `title` so shared defs keep their canonical name.

using System.Text;
using System.Text.Json.Nodes;
using NJsonSchema;
using NJsonSchema.CodeGeneration;
using NJsonSchema.CodeGeneration.CSharp;

var here = AppContext.BaseDirectory;
// tools/Generator/bin/<cfg>/net8.0/ → repo dotnet/ is four levels up, spec is sibling.
var dotnetDir = FindUpwards(here, "spec") ?? throw new DirectoryNotFoundException("Could not locate the spec/ directory above the generator.");
var specDir = Path.Combine(dotnetDir, "spec");
var outFile = Path.Combine(dotnetDir, "dotnet", "src", "Generated", "Types.cs");

// Allow explicit overrides: Generator <specDir> <outFile>
if (args.Length >= 1) specDir = Path.GetFullPath(args[0]);
if (args.Length >= 2) outFile = Path.GetFullPath(args[1]);

Console.WriteLine($"spec dir : {specDir}");
Console.WriteLine($"out file : {outFile}");

const string Namespace = "SmooAI.SmoothOperator.Generated";

var settings = new CSharpGeneratorSettings
{
    Namespace = Namespace,
    JsonLibrary = CSharpJsonLibrary.SystemTextJson,
    GenerateDataAnnotations = false,
    ClassStyle = CSharpClassStyle.Poco,
    GenerateOptionalPropertiesAsNullable = true,
    GenerateNullableReferenceTypes = true,
    TypeNameGenerator = new TitleFirstTypeNameGenerator(),
};

var files = ListSchemaFiles(specDir);

// Build ONE merged schema document whose `definitions` holds every named type from
// every spec file (keyed by its title), plus a synthetic root that $refs each one.
// NJsonSchema generates each definition exactly once with its canonical title-based
// name, resolves all #/definitions/... refs (including def-to-def), and deduplicates
// shared types (ErrorObject, ConversationMessage, GeneralAgentResponse) for free.
var definitions = new JsonObject();
var sourceComments = new List<string>();

foreach (var file in files)
{
    var rel = Path.GetRelativePath(specDir, file).Replace('\\', '/');
    var raw = ParseSanitized(await File.ReadAllTextAsync(file)).AsObject();

    foreach (var (title, node) in ExpandSchemas(raw))
    {
        if (definitions.ContainsKey(title))
            continue; // shared def already collected from an earlier file
        definitions[title] = node;
        sourceComments.Add($"//   {title,-34} ← {rel}");
    }
}

var rootProperties = new JsonObject();
foreach (var kv in definitions)
    rootProperties[kv.Key] = new JsonObject { ["$ref"] = $"#/definitions/{kv.Key}" };

var merged = new JsonObject
{
    ["title"] = "GeneratedRoot",
    ["type"] = "object",
    ["additionalProperties"] = false,
    ["properties"] = rootProperties,
    ["definitions"] = definitions,
};

var mergedSchema = await JsonSchema.FromJsonAsync(merged.ToJsonString());
var generated = new CSharpGenerator(mergedSchema, settings).GenerateFile();
var body = ExtractNamespaceBody(generated);
// Drop the synthetic `GeneratedRoot` wrapper class — it only existed to anchor refs.
body = RemoveDeclaration(body, "GeneratedRoot");

// net8's JsonStringEnumConverter<T> ignores [EnumMember], so swap it for our
// EnumMemberStringConverter<T> which honors the kebab/snake-cased wire enum values.
body = body.Replace(
    "System.Text.Json.Serialization.JsonStringEnumConverter<",
    "SmooAI.SmoothOperator.Generated.EnumMemberStringConverter<");

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("//     AUTO-GENERATED — do not edit by hand.");
sb.AppendLine("//");
sb.AppendLine("//     Generated from the JSON Schemas in spec/ by tools/Generator (NJsonSchema).");
sb.AppendLine("//     Run `dotnet run --project tools/Generator` to regenerate after a schema change.");
sb.AppendLine("//");
sb.AppendLine("//     Named types and their source schema:");
foreach (var c in sourceComments)
    sb.AppendLine(c);
sb.AppendLine("// </auto-generated>");
sb.AppendLine("#nullable enable");
sb.AppendLine("#pragma warning disable // Disable all warnings in generated code");
sb.AppendLine();
sb.AppendLine($"namespace {Namespace}");
sb.AppendLine("{");
foreach (var line in body.Trim('\n').Split('\n'))
    sb.AppendLine(line.Length == 0 ? string.Empty : "    " + line);
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outFile)!);
await File.WriteAllTextAsync(outFile, sb.ToString());

var typeCount = body.Split('\n').Count(l =>
{
    var t = l.TrimStart();
    return t.StartsWith("public partial class ") || t.StartsWith("public enum ");
});
Console.WriteLine($"Wrote {outFile} ({typeCount} types from {files.Count} schema files).");

// ───────────────────────────────── helpers ──────────────────────────────────

// A couple of spec files carry a duplicate `description` key on the same object
// (legal-ish JSON that JsonNode parses but throws on first dictionary access).
// Re-serialize through JsonDocument (last-key-wins) to produce a clean tree.
static JsonNode ParseSanitized(string json)
{
    using var doc = System.Text.Json.JsonDocument.Parse(json);
    var clean = SanitizeElement(doc.RootElement);
    return clean;
}

static JsonNode SanitizeElement(System.Text.Json.JsonElement el)
{
    switch (el.ValueKind)
    {
        case System.Text.Json.JsonValueKind.Object:
            var obj = new JsonObject();
            foreach (var prop in el.EnumerateObject())
                obj[prop.Name] = SanitizeElement(prop.Value); // last key wins
            return obj;
        case System.Text.Json.JsonValueKind.Array:
            var arr = new JsonArray();
            foreach (var item in el.EnumerateArray())
                arr.Add(SanitizeElement(item));
            return arr;
        default:
            return JsonNode.Parse(el.GetRawText())!;
    }
}

static string? FindUpwards(string start, string childDirName)
{
    var dir = new DirectoryInfo(start);
    while (dir is not null)
    {
        if (Directory.Exists(Path.Combine(dir.FullName, childDirName)))
            return dir.FullName;
        dir = dir.Parent;
    }
    return null;
}

static List<string> ListSchemaFiles(string specDir)
{
    var result = new List<string>();
    foreach (var sub in new[] { "", "actions", "events", "domain" })
    {
        var dir = string.IsNullOrEmpty(sub) ? specDir : Path.Combine(specDir, sub);
        if (!Directory.Exists(dir)) continue;
        foreach (var f in Directory.GetFiles(dir, "*.schema.json"))
            result.Add(f);
    }
    result.Sort(StringComparer.Ordinal);
    return result;
}

// Decompose a spec file into the named types it contributes to the merged document.
//
//  - oneOf-over-$defs files (envelope, actions): each named $def becomes its own
//    type, keyed by its title (Request → SendMessageRequest, etc.). Any *nested*
//    $defs are hoisted out so they too become top-level definitions.
//  - flat object files (events, domain): the whole schema is one type keyed by its
//    title; nested $defs (e.g. message.schema.json's MessageContent / ContentItem)
//    are hoisted into top-level definitions.
//
// Every #/$defs/... ref is rewritten to #/definitions/... so NJsonSchema (which
// resolves its native `definitions` keyword, including def-to-def refs, but not
// draft 2020-12 `$defs`) can wire them up. Returned nodes carry no $defs of their
// own — the shared definitions map lives at the merged document root.
static IEnumerable<(string Title, JsonNode Node)> ExpandSchemas(JsonObject schema)
{
    var hasOneOf = schema["oneOf"] is JsonArray;
    var defs = schema["$defs"] as JsonObject;
    var fileTitle = schema["title"]?.GetValue<string>() ?? "Type";

    if (hasOneOf && defs is not null && defs.Count > 0)
    {
        foreach (var kv in defs)
        {
            var def = kv.Value!.DeepClone().AsObject();
            var nestedDefs = def["$defs"] as JsonObject;
            def.Remove("$defs");
            var title = def["title"]?.GetValue<string>() ?? $"{fileTitle}{kv.Key}";
            def["title"] = title;
            yield return (title, RewriteRefs(def));

            // Hoist any nested $defs (rare in actions, but be safe).
            if (nestedDefs is not null)
                foreach (var nested in HoistDefs(nestedDefs))
                    yield return nested;
        }
        yield break;
    }

    // Flat top-level object (events, domain).
    var clone = schema.DeepClone().AsObject();
    var ownDefs = clone["$defs"] as JsonObject;
    clone.Remove("$defs");
    var t = clone["title"]?.GetValue<string>() ?? fileTitle;
    clone["title"] = t;
    yield return (t, RewriteRefs(clone));

    if (ownDefs is not null)
        foreach (var nested in HoistDefs(ownDefs))
            yield return nested;
}

// Turn a $defs map into a sequence of top-level (title, node) definitions, keyed by
// each def's title, with refs rewritten.
static IEnumerable<(string Title, JsonNode Node)> HoistDefs(JsonObject defs)
{
    foreach (var kv in defs)
    {
        var def = kv.Value!.DeepClone().AsObject();
        var inner = def["$defs"] as JsonObject;
        def.Remove("$defs");
        var title = def["title"]?.GetValue<string>() ?? kv.Key;
        def["title"] = title;
        yield return (title, RewriteRefs(def));
        if (inner is not null)
            foreach (var n in HoistDefs(inner))
                yield return n;
    }
}

// Recursively rewrite every "$ref": "#/$defs/X" → "#/definitions/X".
static JsonNode RewriteRefs(JsonNode node)
{
    switch (node)
    {
        case JsonObject obj:
            foreach (var key in obj.Select(p => p.Key).ToList())
            {
                var child = obj[key];
                if (key == "$ref" && child is JsonValue v && v.TryGetValue<string>(out var s))
                {
                    obj[key] = s.Replace("#/$defs/", "#/definitions/");
                }
                else if (child is not null)
                {
                    obj[key] = RewriteRefs(child.DeepClone());
                }
            }
            return obj;
        case JsonArray arr:
            for (var i = 0; i < arr.Count; i++)
                if (arr[i] is not null)
                    arr[i] = RewriteRefs(arr[i]!.DeepClone());
            return arr;
        default:
            return node;
    }
}

// Remove a single top-level declaration (class/enum) and its leading attribute
// lines by name from the generated body. Used to strip the synthetic GeneratedRoot.
static string RemoveDeclaration(string source, string declName)
{
    var lines = source.Split('\n');
    var kept = new List<string>();
    var depth = 0;
    var i = 0;

    while (i < lines.Length)
    {
        var line = lines[i];
        var trimmed = line.TrimStart();

        if (depth == 0 && TryGetDeclName(trimmed, out var name) && name == declName)
        {
            // Walk back over already-kept attribute / comment lines that decorate this decl.
            while (kept.Count > 0)
            {
                var prev = kept[^1].TrimStart();
                if (prev.StartsWith('[') || prev.StartsWith("//") || prev.Length == 0)
                    kept.RemoveAt(kept.Count - 1);
                else
                    break;
            }
            // Skip the declaration block itself. NJsonSchema puts the opening brace
            // on its own line, so advance until we've opened and closed it.
            var blockDepth = 0;
            var openedBrace = false;
            while (i < lines.Length)
            {
                UpdateDepth(lines[i], ref blockDepth);
                if (blockDepth > 0) openedBrace = true;
                i++;
                if (openedBrace && blockDepth == 0) break;
            }
            continue;
        }

        kept.Add(line);
        UpdateDepth(line, ref depth);
        i++;
    }

    return string.Join('\n', kept);
}

// NJsonSchema wraps generated types in `namespace X { ... }` boilerplate plus a file
// header. Extract just the inner declarations so we can re-wrap them all in one
// namespace with consistent indentation.
static string ExtractNamespaceBody(string generated)
{
    var open = generated.IndexOf('{');
    var close = generated.LastIndexOf('}');
    if (open < 0 || close < 0 || close <= open) return generated;
    var inner = generated.Substring(open + 1, close - open - 1);

    // Strip a leading `#pragma warning disable ...` line that NJsonSchema injects
    // inside the namespace (we add one centrally at the top of the file).
    var lines = inner.Split('\n')
        .Where(l => !l.TrimStart().StartsWith("#pragma warning disable"))
        .ToList();

    // Dedent by the common leading 4-space indent NJsonSchema applies inside the
    // namespace so our central re-indent produces clean output.
    var dedented = lines.Select(l => l.StartsWith("    ") ? l.Substring(4) : l);
    return string.Join('\n', dedented).Trim('\n');
}

static void UpdateDepth(string line, ref int depth)
{
    foreach (var ch in line)
    {
        if (ch == '{') depth++;
        else if (ch == '}') depth = Math.Max(0, depth - 1);
    }
}

static bool TryGetDeclName(string trimmed, out string? name)
{
    name = null;
    foreach (var kw in new[] { "public partial class ", "public class ", "public enum ", "public partial interface ", "public interface " })
    {
        if (trimmed.StartsWith(kw))
        {
            var rest = trimmed.Substring(kw.Length);
            var end = rest.IndexOfAny(new[] { ' ', '\r', '\t', ':', '{' });
            name = end < 0 ? rest.Trim() : rest.Substring(0, end).Trim();
            return !string.IsNullOrEmpty(name);
        }
    }
    return false;
}

// Prefer a referenced schema's `title` over the property-derived name hint so
// shared $defs keep their canonical names (ConversationMessage, not Messages).
sealed class TitleFirstTypeNameGenerator : DefaultTypeNameGenerator
{
    public override string Generate(JsonSchema schema, string? typeNameHint, IEnumerable<string> reservedTypeNames)
    {
        var actual = schema.ActualSchema;
        if (!string.IsNullOrEmpty(actual.Title))
            return base.Generate(schema, actual.Title, reservedTypeNames);
        return base.Generate(schema, typeNameHint, reservedTypeNames);
    }
}
